[package]
name = "rsdk"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
reqwest = { version = "0.12", features = ["blocking", "stream"] }
directories = "5"
log = "0.4"
env_logger = "0.11"
symlink = "0.1"
#colored = "2.1"
anyhow = "1.0"
zip = "2.2"
http-cache-reqwest = "0.14"
reqwest-middleware = { version = "0.3.3" }
tokio = "1.41.0"
bytes = "1.8"
indicatif = "0.17"
futures-util = "0.3"
tempfile = "3"
