#!/usr/bin/env fish

# Build the executable
if test "$argv[1]" = "--debug"
    cargo +nightly build
    set rsdk_exe "target/debug/rsdk"
else
    cargo build --release
    set rsdk_exe "target/release/rsdk"
end

# Install executable to bin dir
set -l rsdk_home ~/.rsdk
set -l rsdk_bin $rsdk_home/bin
mkdir -p $rsdk_bin
set -l rsdk_bin_exe "$rsdk_bin/rsdk"
echo "Copy $rsdk_exe to $rsdk_bin_exe"
if test -f $rsdk_bin_exe
    rm $rsdk_bin_exe
end
cp $rsdk_exe $rsdk_bin_exe
set -l rsdk_exe "$rsdk_bin_exe"

# Install functions
set -l fish_plugin_dir ~/.config/fish/functions
mkdir -p $fish_plugin_dir
echo "Generate $fish_plugin_dir/rsdk.fish using rsdk path $rsdk_bin_exe"
cat templates/fish/rsdk.fish | sed "s|PUT_RSDK_PATH_HERE|$rsdk_bin_exe|g" > $fish_plugin_dir/rsdk.fish

# Install plugin
set -l fish_conf_dir ~/.config/fish/conf.d
mkdir -p $fish_conf_dir
cp templates/fish/rsdk_plugin.fish $fish_conf_dir
echo "Installed fish plugin in $fish_conf_dir"

# Initialize and refresh rsdk in session
rsdk init
echo "Refreshed rsdk in session"
