#!/usr/bin/bash

# Build the executable using cargo
if [[ "$1" == "--debug" ]]; then
    cargo build
    rsdk_exe="target/debug/rsdk"
else
    cargo build --release
    rsdk_exe="target/release/rsdk"
fi

rsdk_home=~/.rsdk
rsdk_bin="$rsdk_home"/bin

mkdir -p $rsdk_home/bin
cp $rsdk_exe "$rsdk_bin"

template_src=templates/bash/rsdk.bash
template_dst=$rsdk_bin/rsdk.bash

cat $template_src | sed "s|PUT_RSDK_PATH_HERE|$rsdk_exe|g" > "$template_dst"

# Output completion message
echo "Installed rsdk bash to $rsdk_home"
echo "Run 'source $template_dst' to activate rsdk now"
echo "Run 'echo \"source $template_dst'\" >> ~/.bashrc' to make it permanent"