$script:RsdkBinary = Join-Path (Join-Path $PSScriptRoot '..\..\bin') 'rsdk.exe'

function Invoke-Rsdk {
    [CmdletBinding()]
    param(
        [Parameter(Position = 0)] [string] $Command = '--help',
        [Parameter(ValueFromRemainingArguments = $true, Position = 1)] [string[]] $Arguments
    )
    $temporaryFile = New-TemporaryFile
    try {
        $argumentList = @('--shell', 'powershell', '--envout', $temporaryFile.FullName, $Command) + @($Arguments)
        & $script:RsdkBinary @argumentList
        if ((Test-Path -LiteralPath $temporaryFile.FullName) -and (Get-Item -LiteralPath $temporaryFile.FullName).Length -gt 0) {
            Invoke-Expression (Get-Content -LiteralPath $temporaryFile.FullName -Raw)
        }
        # No `return $exitCode`: it would emit the exit code to the pipeline
        # (printed after the command output). `$LASTEXITCODE` already reflects
        # the binary's status — the cmdlets above don't touch it.
    } finally {
        Remove-Item -LiteralPath $temporaryFile.FullName -Force -ErrorAction SilentlyContinue
    }
}

Set-Alias -Name rsdk -Value Invoke-Rsdk -Scope Script

# Register tab-completions generated by the installed binary so they always
# match the CLI. Best-effort: a missing/failing binary must not break import.
$script:RsdkCompletions = & $script:RsdkBinary completions powershell 2>$null
if ($LASTEXITCODE -eq 0 -and $script:RsdkCompletions) {
    Invoke-Expression ($script:RsdkCompletions -join "`n")
}

Export-ModuleMember -Function Invoke-Rsdk -Alias rsdk
