name: Build and Release for Windows and Debian

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v1.0.0, v2.1.3, etc.

jobs:
  windows-build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          target: x86_64-pc-windows-msvc

      - name: Use Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Build the project
        run: cargo build --release --target x86_64-pc-windows-msvc

      - name: Generate PowerShell Module
        run: |
          $Source = "templates\\powershell"
          $Destination = "target\\dist\\powershell"
          & build\windows\Module-Template.ps1 -SourceDir $Source -DestinationDir $Destination -ExePath "rsdk.exe"
        shell: pwsh

      - name: Move rsdk binary to dist folder
        run: |
          $Source = "target\\x86_64-pc-windows-msvc\\release\\rsdk.exe"
          $Destination = "target\\dist\\rsdk.exe"
          Move-Item -Path $Source -Destination $Destination -Force
        shell: pwsh

      - name: Upload Windows Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rsdk-windows-x86_64-${{ github.ref_name }}
          path: target\dist

  debian-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu

      - name: Use Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Build the project
        run: cargo build --release --target x86_64-unknown-linux-gnu

      - name: Move rsdk binary to dist folder
        run: mv target/x86_64-unknown-linux-gnu/release/rsdk target/dist/rsdk

      - name: Generate Bash Plugin
        run: bash ./build/unix/generate-plugin.sh templates/bash target/dist/bash rsdk

      - name: Generate Bash Plugin Script
        run: bash ./build/unix/generate-plugin.sh templates/fish target/dist/fish rsdk

      - name: Upload Linux Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rsdk-linux-x86_64-${{ github.ref_name }}
          path: target/dist
