name: Build and Release for Windows and Debian

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v1.0.0, v2.1.3, etc.

jobs:
  windows-build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          target: x86_64-pc-windows-msvc

      - name: Build the project
        run: cargo build --release --target x86_64-pc-windows-msvc

      - name: Generate PowerShell Module
        run: |
          $Source = "$(pwd)\templates\powershell"
          $Destination = "$(pwd)\target\powershell"
          $ExePath = "rsdk.exe"
          & build\windows\Module-Template.ps1 -SourceDir $Source -DestinationDir $Destination -ExePath $ExePath
        shell: pwsh

      - name: Create ZIP package for Windows
        run: |
          $version = '${{ github.ref_name }}'
          $arch = "x86_64"
          $output = "rsdk-windows-$version-$arch.zip"
          Compress-Archive -Path "target/x86_64-pc-windows-msvc/release/rsdk.exe", "target/powershell" -DestinationPath $output -Force
        shell: pwsh

      - name: Upload Windows ZIP
        uses: actions/upload-artifact@v4
        with:
          name: rsdk-windows-${{ github.ref_name }}-x86_64
          path: rsdk-windows-${{ github.ref_name }}-x86_64.zip

  debian-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu

      - name: Build the project
        run: cargo build --release --target x86_64-unknown-linux-gnu

      - name: Create tar.gz package for Debian
        run: |
          version=${GITHUB_REF_NAME}
          arch=$(uname -m)
          output="rsdk-debian-${version}-${arch}.tar.gz"
          tar -czvf $output -C target/x86_64-unknown-linux-gnu/release rsdk
        shell: bash

      - name: Upload Debian tar.gz
        uses: actions/upload-artifact@v4
        with:
          name: rsdk-debian-${{ github.ref_name }}-x86_64
          path: rsdk-debian-${{ github.ref_name }}-x86_64.tar.gz
