name: Build and Release for Windows

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v1.0.0, v2.1.3, etc.

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Install Rust
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-pc-windows-msvc

      # Extract the version number from the tag (e.g., v1.0.0)
      - name: Extract version number
        id: get_version
        run: echo "::set-output name=VERSION::${GITHUB_REF#refs/tags/v}"

      # Build the project
      - name: Build the project
        run: cargo build --release --target x86_64-pc-windows-msvc

      # Create the ZIP package with version number in the name
      - name: Create ZIP package
        run: |
          $version = '${{ steps.get_version.outputs.VERSION }}'
          $output = "rsdk-windows-$version.zip"
          Compress-Archive -Path "target/x86_64-pc-windows-msvc/release/rsdk.exe", "powershell/*" -DestinationPath $output
        shell: pwsh

      # Upload the ZIP archive as an artifact
      - name: Upload Release ZIP
        uses: actions/upload-artifact@v3
        with:
          name: rsdk-windows-${{ steps.get_version.outputs.VERSION }}
          path: rsdk-windows-${{ steps.get_version.outputs.VERSION }}.zip