name: Build and Release for Windows

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v1.0.0, v2.1.3, etc.

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Install Rust
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-pc-windows-msvc

      # Build the project
      - name: Build the project
        run: cargo build --release --target x86_64-pc-windows-msvc

      # Upload binary as an artifact
      - name: Upload Release Binary
        uses: actions/upload-artifact@v3
        with:
          name: rsdk-windows
          path: target/x86_64-pc-windows-gnu/release/rsdk.exe

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Upload the binary to the GitHub release
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: target/x86_64-pc-windows-gnu/release/rsdk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token automatically provided by Actions
