name: Build and Release for Windows and Debian

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v1.0.0, v2.1.3, etc.

jobs:
  windows-build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          target: x86_64-pc-windows-msvc

      - name: Build the project
        run: cargo build --release --target x86_64-pc-windows-msvc

      - name: Generate PowerShell Module
        run: |
          $Source = "templates\powershell"
          $Destination = "target\powershell"
          & build\windows\Module-Template.ps1 -SourceDir $Source -DestinationDir $Destination -ExePath "rsdk.exe"
        shell: pwsh

      - name: Upload Windows Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rsdk-windows-${{ github.ref_name }}-x86_64
          path: |
            target\**\rsdk.exe
            target\**\*.psd1
            target\**\*.psm1

  debian-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu

      - name: Build the project
        run: cargo build --release --target x86_64-unknown-linux-gnu

      - name: Generate Bash Plugin
        run: bash ./build/unix/generate-plugin.sh templates/bash target/bash rsdk

      - name: Generate Bash Plugin Script
        run: bash ./build/unix/generate-plugin.sh templates/fish target/fish rsdk

      - name: Upload Linux Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rsdk-linux-${{ github.ref_name }}-x86_64
          path: |
            target/x86_64-unknown-linux-gnu/release/rsdk
            target/**/*.fish
            target/**/*.bash
